# Configuración atómica e independiente para producción
spring.datasource.url=jdbc:postgresql://dpg-d8er7lt7vvec73duatng-a.frankfurt-postgres.render.com:5432/vinylfreak
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Configuración del Driver
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Estrategia de actualización de tablas (mantiene tus datos a salvo)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false