spring.datasource.url=jdbc:postgresql://localhost:5432/vinylfreak_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# 'update' leerá tus POJOs y creará las tablas que falten o añadirá columnas nuevas.
spring.jpa.hibernate.ddl-auto=update

# Esto te permite ver las sentencias CREATE TABLE y JOIN que hace Hibernate.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

google.clientId=655904218710-daeref60csq47aj2hgqnkqepnmc3k7a2.apps.googleusercontent.com